apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fincore-bootstrap
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/rowjay007/fincore-mevi.git
    targetRevision: HEAD
    path: infra/gitops/apps
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
