image:
  tag: latest

replicaCount: 1

services:
  api-gateway:
    env:
      GATEWAY_HTTP_ADDR: ":8080"
  identity-service:
    env:
      IDENTITY_HTTP_ADDR: ":8084"
  auth-service:
    env:
      AUTH_HTTP_ADDR: ":8082"
  account-service:
    env:
      ACCOUNT_HTTP_ADDR: ":8080"
  ledger-service:
    env:
      LEDGER_HTTP_ADDR: ":8083"
