apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fincore-service.fullname" . }}
  labels:
    {{- include "fincore-service.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "fincore-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "fincore-service.selectorLabels" . | nindent 8 }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
    spec:
      securityContext:
        {{- toYaml .Values.securityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          ports:
            - name: grpc
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          livenessProbe:
            grpc:
              port: {{ .Values.service.port }}
          readinessProbe:
            grpc:
              port: {{ .Values.service.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "fincore-service.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    {{- include "fincore-service.selectorLabels" . | nindent 4 }}
