apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fincore-service.fullname" . }}
  labels:
    {{- include "fincore-service.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "fincore-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- if .Values.vault.enabled }}
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: {{ .Values.vault.role | quote }}
        vault.hashicorp.com/agent-inject-secret-config: {{ .Values.vault.secretPath | quote }}
        {{- end }}
      labels:
        {{- include "fincore-service.selectorLabels" . | nindent 8 }}
        {{- if .Values.spire.enabled }}
        spiffe.io/spiffe-id: "true"
        {{- end }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
            - name: grpc
              containerPort: {{ .Values.service.grpcPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
          readinessProbe:
            httpGet:
              path: /readyz
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if .Values.spire.enabled }}
          volumeMounts:
            - name: spire-agent-socket
              mountPath: /run/spire/sockets
              readOnly: true
          {{- end }}
      {{- if .Values.spire.enabled }}
      volumes:
        - name: spire-agent-socket
          hostPath:
            path: {{ .Values.spire.agentSocketPath }}
            type: Socket
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "fincore-service.fullname" . }}
  labels:
    {{- include "fincore-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.grpcPort }}
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    {{- include "fincore-service.selectorLabels" . | nindent 4 }}
