agent {
  data_dir = "/run/spire/data"
  log_level = "INFO"
  server_address = "spire-server"
  server_port = "8080"
  socket_path = "/run/spire/sockets/agent.sock"
  trust_domain = "fincore.local"
}

plugins {
  NodeAttestor "join_token" {
    plugin_data {
      # This must match the join token you generate on the server.
      join_token = "dev-join-token"
    }
  }

  WorkloadAttestor "docker" {
    plugin_data {
      docker_socket_path = "/var/run/docker.sock"
    }
  }

  KeyManager "memory" {
    plugin_data {}
  }
}
